#if !defined(AFX_SCENECONTROLDEFAULT_H__CE715B9B_3E6F_4F02_B912_902FE912A7F2__INCLUDED_)
#define AFX_SCENECONTROLDEFAULT_H__CE715B9B_3E6F_4F02_B912_902FE912A7F2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CSceneControlDefault wrapper class

class CSceneControlDefault : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSceneControlDefault)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xdd4b8602, 0x61f1, 0x4528, { 0x82, 0xdf, 0x8b, 0x5a, 0xcc, 0x86, 0x2f, 0x84 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetBackColor(unsigned long newValue);
	unsigned long GetBackColor();
	void SetBorderStyle(long nNewValue);
	long GetBorderStyle();
	void SetEnabled(BOOL bNewValue);
	BOOL GetEnabled();
	void SetAppearance(long nNewValue);
	long GetAppearance();
	void SetMousePointer(long nNewValue);
	long GetMousePointer();
	void SetRefMouseIcon(LPDISPATCH newValue);
	CPicture GetMouseIcon();
	long GetHWnd();
	void AboutBox();
	void LoadSxFile(LPCTSTR sxPath);
	LPUNKNOWN GetScene();
	LPUNKNOWN GetSceneGraph();
	void SetRefSceneGraph(LPUNKNOWN newValue);
	LPUNKNOWN GetSceneViewer();
	LPUNKNOWN GetCamera();
	void SetRefCamera(LPUNKNOWN newValue);
	LPUNKNOWN GetCurrentTool();
	void SetRefCurrentTool(LPUNKNOWN newValue);
	BOOL GetNavigate();
	void SetNavigate(BOOL bNewValue);
	BOOL CheckSxFile(LPCTSTR filename);
	VARIANT GetCustomProperty();
	void SetCustomProperty(const VARIANT& newValue);
	void SetDocumentFilename(LPCTSTR lpszNewValue);
	CString GetDocumentFilename();
	LPDISPATCH GetObject();
	void SetOverrideBackColor(BOOL bNewValue);
	BOOL GetOverrideBackColor();
	void SetShowSceneTips(BOOL bNewValue);
	BOOL GetShowSceneTips();
	void SetTipStyle(long nNewValue);
	long GetTipStyle();
	void SetTipDelay(long nNewValue);
	long GetTipDelay();
	long GetKeyIntercept();
	void SetKeyIntercept(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SCENECONTROLDEFAULT_H__CE715B9B_3E6F_4F02_B912_902FE912A7F2__INCLUDED_)
