#if !defined(AFX_TOCCONTROLDEFAULT_H__9DF7E6F7_CCFF_4444_91FB_E889A44C14A7__INCLUDED_)
#define AFX_TOCCONTROLDEFAULT_H__9DF7E6F7_CCFF_4444_91FB_E889A44C14A7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CTOCControlDefault wrapper class

class CTOCControlDefault : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTOCControlDefault)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa0f9a9a2, 0x4a3f, 0x4888, { 0x82, 0x6f, 0xca, 0x2b, 0xfa, 0x23, 0xcf, 0x17 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetEnabled(BOOL bNewValue);
	BOOL GetEnabled();
	long GetHWnd();
	void SetMousePointer(long nNewValue);
	long GetMousePointer();
	void SetRefMouseIcon(LPDISPATCH newValue);
	CPicture GetMouseIcon();
	long GetAppearance();
	void SetAppearance(long nNewValue);
	void SetBorderStyle(long nNewValue);
	long GetBorderStyle();
	void AboutBox();
	LPUNKNOWN GetActiveView();
	LPDISPATCH GetBuddy();
	void HitTest(long x, long y, long* ItemType, LPUNKNOWN* BasicMap, LPUNKNOWN* Layer, LPUNKNOWN* Unk, VARIANT* Data);
	void Update();
	void SetActiveView(LPUNKNOWN ActiveView);
	long GetLayerVisibilityEdit();
	void SetLayerVisibilityEdit(long nNewValue);
	long GetLabelEdit();
	void SetLabelEdit(long nNewValue);
	VARIANT GetCustomProperty();
	void SetCustomProperty(const VARIANT& newValue);
	void SetBuddyControl(LPDISPATCH pTOCBuddy);
	LPDISPATCH GetObject();
	long GetKeyIntercept();
	void SetKeyIntercept(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TOCCONTROLDEFAULT_H__9DF7E6F7_CCFF_4444_91FB_E889A44C14A7__INCLUDED_)
